language: python
python:
    - "2.7"
# command to install dependencies
services:
    - redis-server
install:
    - "pip install -r req.txt"
# command to run tests
script: "nosetests --cov-config .coveragerc"
after_success: coveralls
