language: python
python:
    - "2.7"
# command to install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq redis-server
install:
    - "pip install -r req.txt"
# command to run tests
script: "nosetests --cov-config .coveragerc"
after_success: coveralls
